import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className="grid w-full"
          style={{
            minHeight: "100vh",
            gridTemplateColumns: "10% 80% 10%",
            gridTemplateRows:
              "minmax(10vh, auto) minmax(80vh, auto) minmax(10vh, auto)",
          }}
        >
          {/* Top row */}
          <div className="border-b border-r"></div>
          <div className="border-b border-r border-l"></div>
          <div className="border-b border-l"></div>

          {/* Middle row */}
          <div className="border-b border-r"></div>
          <div className="border-b border-r border-l">{children}</div>
          <div className="border-b border-l"></div>

          {/* Bottom row */}
          <div className="border-r"></div>
          <div className="border-r border-l"></div>
          <div className="border-l"></div>
        </div>
      </body>
    </html>
  );
}
